services:
  - type: web
    name: your-service-name
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget --no-install-recommends
      apt-get install -y --no-install-recommends \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libdbus-1-3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libxss1 \
        libxtst6 \
        xdg-utils \
        lsb-release \
        libgbm-dev \
        curl \
        libnss3-tools \
        libgconf-2-4 \
        google-chrome-stable
      npm install
    startCommand: npm start
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
